# Generated by Django 3.0.3 on 2020-06-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
    ]
