# Generated by Django 3.0.3 on 2020-06-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_record_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.AlterField(
            model_name='record',
            name='from_ts',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
