# Generated by Django 3.0.3 on 2020-06-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rooms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
